version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    user: "472:472" 
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  grafana-storage: 
